### ISSUE TITLE
Oof.

### ISSUE THREAD

**Issue by VelocityDesign** [MikeDev101/Yoom#1]
I already made a Yoom! Platform. Want to join forces?

**Comment by MikeDev101** [comment]
Yees

**Comment by ConvexPolygon** [comment]
It has no GUI yet. It has chat, forums, user blogs, ect.

**Comment by MikeDev101** [comment]
I don't mind, but is there a preview I can test with? I'm currently in the process of writing a new version of Yoom with the basics as well, and then I'm going to figure out a proper GUI.
